### ISSUE TITLE
Next version TODO

### ISSUE THREAD

**Issue by JSidrach** [JSidrach/my-ubuntu#1]
Next version of the scripts should include (at least) the following modifications:

- [x] Fix (or remove) specific workspace windows
- [x] Improve terminal theme and colors
- [x] Include and set desktop background
- [x] Change calls to launcher calls

**Comment by JSidrach** [comment]
Done in 1e5fead
